### PR TITLE
feature extractor

### PR DESCRIPTION
**Pull request by attitudechunfeng**
run examples/c3d_ucf101/feature_extractor.sh for feature extraction and run
read_binary_blob.m to parse the binary feature file. Most usages follow the original C3D.

### CODE REVIEW

**Comment by chuckcho** [comment]
Awesome. Thanks for the contribution. Before I merge, could you take a look at Travis and fix why it fails? E.g. https://travis-ci.org/chuckcho/video-caffe/jobs/119458894 shows ```tools/predict.cpp:18:26: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.```
Also, Caffe has a policy of running through lint (`make lint`) for code integrity/styling consistency.

**Comment by attitudechunfeng** [comment]
Hi, I've checked the code again and fixed errors listed in travis, please try to merge again?

**Comment by chuckcho** [comment]
Can you commit your changes? Travis will rerun if you push your changes to your existing PR.

**Comment by chuckcho** [comment]
Thanks for the fixes. Merge now.

**Pull request merged**
