### PR TITLE
Support cuDNN v5

### LINKED ISSUE #18: support cuDNN V5?
Hi @chuckcho 

I compiled this video-caffe with cuDNN v5.0.5 for CUDA 8.0, but got errors like following.

So, does this version of Caffe not support cuDNN v5?

Best,
Rui

```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   v1.0-rc0-3653-g0089f35-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.0)
--   lmdb              :   Yes (ver. 0.9.14)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 5.0.5)
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.9)
--   Libraries         :   /usr/lib64/libpython2.7.so (ver 2.7.9)
--   NumPy             :   /usr/lib64/python2.7/site-packages/numpy/core/include (ver 1.10.4)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.6)
--   config_file       :   /home_local/C3D/new/video-caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home_local/C3D/new/video-caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home_local/C3D/new/video-caffe/build
```

`host:/home_local/C3D/new/video-caffe/build> make clean`
`hosr:/home_local/C3D/new/video-caffe/build> make all`

```
[  1%] Running C++/Python protocol buffer compiler on /home_local/C3D/new/video-caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  1%] Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_eltwise_layer.cu.o
/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(152): error: argument of type "int *" is incompatible with parameter of type "cudnnTensorFormat_t *"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(153): error: too few arguments in function call

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(186): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(186): error: too few arguments in function call

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(209): error: argument of type "std::size_t" is incompatible with parameter of type "cudnnNanPropagation_t"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(209): error: argument of type "int *" is incompatible with parameter of type "int"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(209): error: too few arguments in function call

7 errors detected in the compilation of "/tmp/tmpxft_00007f09_00000000-5_eltwise_layer.cpp4.ii".
CMake Error at cuda_compile_generated_eltwise_layer.cu.o.cmake:266 (message):
  Error generating file
  /home_local/C3D/new/video-caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_eltwise_layer.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:469: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_eltwise_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_eltwise_layer.cu.o] Error 1
CMakeFiles/Makefile2:235: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by futurely**
This closes #18.

### CODE REVIEW

**Comment by chuckcho** [comment]
@futurely awesome! thanks for your contribution. before i merge, could you check errors @https://travis-ci.org/chuckcho/video-caffe/builds/139182750? they look like cosmetic lint errors, but i usually make everything lint-error/warning free. thanks!

**Comment by futurely** [comment]
https://travis-ci.org/chuckcho/video-caffe/builds/139187928

**Comment by futurely** [comment]
So does cuDNN v5.
https://travis-ci.org/chuckcho/video-caffe/builds/139197823

**Comment by chuckcho** [comment]
thanks for awesome contribution to the long-awaited feature! merging now

**Pull request merged**
